services:
    sonata.admin.post:
        class: iTFLS\Card\ApiBundle\Admin\CardAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Api1", label: "Card" }
        arguments:
            - ~
            - iTFLS\Card\ApiBundle\Entity\Card
            - ~
        calls:
            - [ setTranslationDomain, [iTFLSCardApiBundle]]